### ISSUE TITLE
yarprobotinterface cannot open on Ubuntu, while running tutorial_on_Cartesian-interface-system?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_cartesian-interface#2]
How to fix this kind of error? 
![image](https://user-images.githubusercontent.com/55526431/69321867-32c34e00-0c87-11ea-9d28-b2887bf54789.png)

**Comment by pattacini** [comment]
Try to start over from scratch, by doing a power cycle of your machine (shut it down and turn it on again). This has the advantage that hanging modules would be cleaned up.

When you find yourself in analogous situations, you might use `ps aux` to check whether modules that you're going to launch are already hanging stuck.

**Comment by YANGGANG1971** [comment]
Type ps aux, it seems that yarprobotinterface module is not hanging stuck.
![image](https://user-images.githubusercontent.com/55526431/69507234-300d7500-0f75-11ea-85f6-89dfbc0895e4.png)

Type yarprobotinterface on Ubuntu, the error is as follows.
![image](https://user-images.githubusercontent.com/55526431/69506965-2f281380-0f74-11ea-981c-d21492130460.png)

**Comment by pattacini** [comment]
The problem is that `yarprobotinterface` fails to start because it doesn't find the file `yarprobotinterface.ini`.

It's likely that you didn't set up the env variable `YARP_DATA_DIRS` correctly.
To do so, try:
```sh
YARP_DATA_DIRS=${path_to_yarp_build}/share/yarp:${path_to_icub-main_build}/share/iCub
```

Once done, you can check that everything's fine by doing:
```sh
$ yarp resource --context yarprobotinterface --from yarprobotinterface.ini
```
and see whether the file gets found.
